### ISSUE TITLE
Mojo exception while renaming from .temp to .zip

### ISSUE THREAD

**Issue by krishananth** [mulesoft/mule-esb-maven-tools#4]
Hello,

I was trying to deploy a mule application to existing stand alone Mule 3.6.1 installation [Windows environment].  Maven is able to start Mule and when deploying it copies the zip file from "/target/project_name.zip" and pastes to $mule_home/apps/project_name.temp folder first.

Later maven tries to rename the .temp file to .zip - where the Mojo exception is happening.
But I see the application got deployed (irrespective of whether the .temp file was renamed to zip).
Not sure what the problem is; error trace is:  
Caused by: org.apache.maven.plugin.MojoExecutionException: Could not rename c:\applications\mule-enterprise-standalone-3.6.1\apps\MavenTestESBProject-1.0.temp to c:\applications\mule-enterprise-standalone-3.6.1\apps\MavenTestESBProject-1.0.zip

Questions:
1) Is this tested in Windows?
2) In Windows, the plugin starts Mule ESB as a windows service.  So I have to use "post-integration-test" phase's 'stop' goal to stop Mule and this automatically uninstalls Mule service.
Is this the expected behaviour.

What is the behaviour in Linux machines?
- ananth

**Comment by fertroya** [comment]
Confirmed on 3.7.2 running on Windows 10.

**Comment by laellyo** [comment]
Hello, I confirm this behavior on Windows 7 + API Gateway 2.1.0 when deploying my package with Maven.

**Comment by wizzlerr** [comment]
Confirmed on 3.3.3 running on Windows 7.

**Comment by asequeira** [comment]
Hello Ananth, 

we are taking a look at this problem. About the usage of post-integration-test, yes, you are supposed to start your standalone server in pre-integration-test phase and stop it in post-integration-test phase.
Regards.

**Comment by JayBofMA** [comment]
This has been an issue in Windows 7 since 3.5.0 running in standalone, at least.

**Comment by LokeshVermaG** [comment]
Hi, i am facing the same issue in windows 10. Is this resolved?

**Comment by samrat-guha** [comment]
Hello - same problem - Win 2012 R2 Maven 3.3.9 Jenkins 2.32.1

Failed to execute goal org.mule.tools.maven:mule-app-maven-plugin:1.2:install (default-install) on project : Could not rename .temp to .zip

apps folder of MULE_HOME has full permissions.

**Comment by exarose** [comment]
In taking cue from previous comment, I've found limited success by changing MULE_HOME environment variable to a sub-folder within the profile path.

[Win 10/Maven 3.3.9/Anypoint 6.2.3]

**Comment by Ashishk-Espire** [comment]
I am also getting same error in window10. It is working fine with bitbucket and bitbucket pipline but in github/jenkins
it is throwing error:

[ERROR] Failed to execute goal org.mule.tools.maven:mule-app-maven-plugin:1.3:install (default-install) on project uia: Could not rename E:\Server\mule-enterprise-standalone-3.8.5\apps\uia-1.0.0-SNAPSHOT.temp to E:\Server\mule-enterprise-standalone-3.8.5\apps\uia-1.0.0-SNAPSHOT.zip -> [Help 1

**Comment by ChazOriginal** [comment]
I have tracked down this problem on Windows to the code in:
org.mule.tools.maven.plugin.app.MuleInstallMojo.copyZipFileToDestDirUsingTempFile(MuleInstallMojo.java:185)
And found that problem is caused by the code not closing the OutputStream before trying to rename the file.
Unlike Linux or Mac, Windows will not allow an open file to be renamed.
The code in copyZipFileToDestDirUsingTempFile() needs to close the 2 streams before calling renameTo().

**Comment by dvmierlo** [comment]
@ChazOriginal Great investigation 👍 Until this is fixed, `mav manual-install` then ;-)

**Comment by ranjeet062** [comment]
Hi,

In my Integration test I have many application interacting with each other. So i have used "mule-maven-plugin" to deploy other apps. find the snap of pom file below.
I have downloaded  all apps zips in my maven repo.

But I am not able to deploy the application.I am getting below error-
1.(If I am giving  full path name with zip extension)
Deploying application [C:\Users\1022864\.m2\repository\com\jci\apps\message-broker\2018.1.0-SNAPSHOT\message-broker-2018.1.0-SNAPSHOT.zip.zip]
[ERROR] Couldn't deploy application [message-broker-2018.1.0-SNAPSHOT.zip] after [60000] miliseconds. Check Mule ESB log
2.(If I am giving  full path name without zip extension)
Failed to execute goal org.mule.tools.maven:mule-maven-plugin:2.1:deploy (deploy) on project integration-test: Couldn't rename [C:\Users\1022864\.m2\repository\com\jci\apps\message-broker\2018.1.0-SNAPSHOT\message-broker-2018.1.0-SNAPSHOT] to [message-broker-2018.1.0-SNAPSHOT] 

 For (used in pom) I gave the maven path of app(tried with and without zip extension) as mentioned in mule documents for mule-maven-plugin.

 
		        <groupId>org.mule.tools.maven</groupId>
		        <artifactId>mule-maven-plugin</artifactId>
		        <version>2.1</version>
		        <configuration>
		            <deploymentType>standalone</deploymentType>
		            <muleHome>C:/mule-enterprise-standalone-3.9.0</muleHome>
		            <muleVersion>${mule.version}</muleVersion>
		        </configuration>
		        <executions>
		            <execution>
			            <id>deploy</id>
			            <phase>pre-integration-test</phase>
			            <goals>
			                <goal>deploy</goal>
			            </goals>
			            <configuration>
			                <application>${app1.location}</application>
			            </configuration>
		       		 </execution>
		            <execution>
		                <id>undeploy</id>
			            <phase>post-integration-test</phase>
			            <goals>
			                <goal>undeploy</goal>
			            </goals>
			            <configuration>
			                <application>${app.1.location}</application>
			            </configuration>
					</execution>
		        </executions>
		    </plugin>

can anyone provide some suggestion on this?

**Comment by ranjeet062** [comment]
Hi,
I also tried with muleesb-maven-plugin. Plugin was able to download the statndalone runtime and placed the applications but not able to deploy the apps and deployenent timeout error got.I had increased the timeout period , even found the same issue.
 find the snipet of pom.

		        <groupId>org.mule.tools.maven</groupId>
		        <artifactId>muleesb-maven-plugin</artifactId>
		        <version>1.0</version>
		        <configuration>
                           <muleVersion>${mule.version}</muleVersion>
                           <applications>
                                   <application>${app.1.location}</application>
                            </applications>
		        </configuration>
		        <executions>
		            <execution>
			            <id>deploy</id>
			            <phase>pre-integration-test</phase>
			            <goals>
			                <goal>deploy</goal>
			            </goals>
			    </execution>
		            <execution>
		                <id>undeploy</id>
			            <phase>post-integration-test</phase>
			            <goals>
			                <goal>undeploy</goal>
			            </goals>
			</execution>
		        </executions>
		    </plugin>
 also instead of deploy, i used start goal as per mule doc says. But got the same issue.
can anyone provide some suggestion on this?

find the error log-

[INFO] --- muleesb-maven-plugin:1.0:deploy (deploy) @ jda-integration-test ---
[INFO] muleDistribution not set, using default artifact: com.mulesoft.muleesb.distributions:mule-ee-distribution-standalone:3.9.0:tar.gz
[INFO] Resolving com.mulesoft.muleesb.distributions:mule-ee-distribution-standalone:tar.gz:3.9.0
[INFO] Copying C:\Users\1022864\.m2\repository\com\mulesoft\muleesb\distributions\mule-ee-distribution-standalone\3.9.0\mule-ee-distribution-standalone-3.9.0.tar.gz to C:\Users\1022864\AnypointStudio\IntegrationTesting\jda-integration-test\target
[INFO] Expanding: C:\Users\1022864\.m2\repository\com\mulesoft\muleesb\distributions\mule-ee-distribution-standalone\3.9.0\mule-ee-distribution-standalone-3.9.0.tar.gz into C:\Users\1022864\AnypointStudio\IntegrationTesting\jda-integration-test\target
[INFO] Using MULE_HOME: C:\Users\1022864\AnypointStudio\IntegrationTesting\jda-integration-test\target\mule-enterprise-standalone-3.9.0
[ERROR] Couldn't deploy application [jda-message-broker] after [60000] miliseconds. Check Mule ESB log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:14 min
[INFO] Finished at: 2018-07-11T11:22:07+05:30
[INFO] Final Memory: 45M/476M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.mule.tools:muleesb-maven-plugin:1.0:deploy (deploy) on project jda-integration-test: Application deployment timeout. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.mule.tools:muleesb-maven-plugin:1.0:deploy (deploy) on project jda-integration-test: Application deployment timeout.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Application deployment timeout.
        at org.mule.tools.muleesb.Deployer.waitForDeployments(Deployer.java:95)
        at org.mule.tools.muleesb.Deployer.execute(Deployer.java:64)
        at org.mule.tools.muleesb.DeployMojo.doExecute(DeployMojo.java:167)
        at org.mule.tools.muleesb.AbstractMuleMojo.execute(AbstractMuleMojo.java:70)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
