### ISSUE TITLE
Error when src/main/resources does not exist

### ISSUE THREAD

**Issue by rikvermeer** [mulesoft/mule-esb-maven-tools#8]
When the resource dir is not existent, the plugin crashes on archiving.
This is annoying while GIT does not commit empty directories.

src/main/resources isn't a directory.
    at org.codehaus.plexus.archiver.AbstractArchiver.addFileSet(AbstractArchiver.java:266)
    at org.codehaus.plexus.archiver.AbstractArchiver.addDirectory(AbstractArchiver.java:252)
    at org.mule.tools.maven.plugin.domain.MuleArchiver.addResources(MuleArchiver.java:38)
    at org.mule.tools.maven.plugin.domain.MuleDomainMojo.addResourcesFile(MuleDomainMojo.java:263)
    at org.mule.tools.maven.plugin.domain.MuleDomainMojo.createMuleDomain(MuleDomainMojo.java:197)
    at org.mule.tools.maven.plugin.domain.MuleDomainMojo.execute(MuleDomainMojo.java:80)

**Comment by yuri1969** [comment]
Any news here?
